Testes com Numpy em Python

In [1]:
import numpy as np
import math

In [2]:
teste = np.array([[0,1,2,3,4],[5,6,7,8,9]])
teste.ndim

2

In [3]:
d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
f = np.linspace(1, 80)
print(f)

[ 1.          2.6122449   4.2244898   5.83673469  7.44897959  9.06122449
 10.67346939 12.28571429 13.89795918 15.51020408 17.12244898 18.73469388
 20.34693878 21.95918367 23.57142857 25.18367347 26.79591837 28.40816327
 30.02040816 31.63265306 33.24489796 34.85714286 36.46938776 38.08163265
 39.69387755 41.30612245 42.91836735 44.53061224 46.14285714 47.75510204
 49.36734694 50.97959184 52.59183673 54.20408163 55.81632653 57.42857143
 59.04081633 60.65306122 62.26530612 63.87755102 65.48979592 67.10204082
 68.71428571 70.32653061 71.93877551 73.55102041 75.16326531 76.7755102
 78.3877551  80.        ]


In [5]:
np.random.rand(4).shape

(4,)

In [6]:
np.linspace(0, 2, 15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [7]:
#pipipipopopo fahrenheit -> celsius

farenheit = np.array([0, -15, -2, -40, 30])

celsius = (farenheit - 32) * (5/9)

celsius

array([-17.77777778, -26.11111111, -18.88888889, -40.        ,
        -1.11111111])

In [8]:
celsius > -20

array([ True, False,  True, False,  True])

In [21]:
A = np.array([[1,2],[0,1]])
B = np.array([[3,4],[2,0]])
print(A@B)

[[7 4]
 [2 0]]


In [22]:
A.shape

(2, 2)

In [23]:
A = np.array([[1,2,3], [0,4,5], [1,6,7]])
B = np.array([[2.3, 1.45, 5.],[2., 3.5, 4.6],[2.9, 3.6, 4.6]])



In [25]:
print(A.dtype)
print(B.dtype)

int64
float64


In [26]:
C = A + B
print(C)
print(C.dtype)

[[ 3.3   3.45  8.  ]
 [ 2.    7.5   9.6 ]
 [ 3.9   9.6  11.6 ]]
float64


In [29]:
B = np.arange (1, 16, 1).reshape(3, 5)
print(B)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


Indexes, Slicing and Iterations

In [40]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
a[[0,1,2], [0,1,1]]

array([1, 4, 6])